### ISSUE TITLE
concurrent transparent planes not being properly display

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#162]
concurrent transparent planes, be that faces of a unit cell (1) or a miller plane / plane set (2-3), are becoming flat within its inner faces. external faces are being displayed without any issues. imgs below

![image](https://cloud.githubusercontent.com/assets/4349542/12629376/d45a4da8-c52e-11e5-882f-7f7368c5e00c.png)

**Comment by ThanosSar** [comment]
done.
