### ISSUE TITLE
atom volume knob not working after preset load

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#163]
[http://crystalwalk.herokuapp.com/#ap](url)
![image](https://cloud.githubusercontent.com/assets/4349542/12629608/c060b066-c52f-11e5-8234-2436f174615c.png)

**Comment by ThanosSar** [comment]
It was a UI issue, I am very confident I solved it but I will write it down to my TODOs list for alex (I have noted down some other small stuff for him :) ) so he can confirm it is ok for sure.
