### ISSUE TITLE
main menu's "auto zoom" not working

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#166]
main menu's auto zoom functionality is not working. have this functionality fixed and enabled by default
![image](https://cloud.githubusercontent.com/assets/4349542/12630684/bc0291ec-c534-11e5-8842-72f504818e8c.png)

**Comment by ekaratzaferis** [comment]
The auto-zoom is feature is working in the following way:

For resolution widths in the range of:
[1300 - inf]     --> 100% zoom
[1100 - 1300] --> 90% zoom
[1000 - 1100] --> 80% zoom
[0 - 1000] ---> 70% zoom

How do you want me to adjust these values?

**Comment by ekaratzaferis** [comment]
I've changed the range to 1400-1200-1000-below for 100-90-80-70%.

I'll implement lower zoom values, see how the app behaves and then reassign new values to the range.
