### ISSUE TITLE
search is case sensitive

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#168]
search needs to be case insensitive. right now you can’t search for “nacl” you need to search for “NaCl” to work
![image](https://cloud.githubusercontent.com/assets/4349542/12631759/59b6f6b2-c53a-11e5-990a-78f26e1143fb.png)
![image](https://cloud.githubusercontent.com/assets/4349542/12631763/5cfdf0d2-c53a-11e5-9dc7-b62f4ee5f0cc.png)

**Comment by lememora** [comment]
@bardella ok!

**Comment by lememora** [comment]
@bardella It should be fixed after https://github.com/gvcm/CWLY/commit/40e8017dfd0f290e10f909c03af08efcfbcbd2b5
but it need to be tested.
