### ISSUE TITLE
loading screen for preset load timming

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#170]
when loading a preset, loading screen is appearing before json file load. this gives user the impression that an error occurred until the json file is fully downloaded and loaded into browser.

this is not an issue once json file is on user's cache.

**Comment by ekaratzaferis** [comment]
Made some adjustments so that the loading screen remains until the JSON file is loaded. I need to test this fix a bit more before closing the issue.

**Comment by bardella** [comment]
alex, I did some testing here and loading is not working... see attachment
![image](https://cloud.githubusercontent.com/assets/4349542/21047009/bc5cf9a8-bdee-11e6-8832-effbf45669c5.png)

**Comment by bardella** [comment]
done :)
