### ISSUE TITLE
crystal framing functionality

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#174]
![image](https://cloud.githubusercontent.com/assets/4349542/12737244/0853fc5e-c93e-11e5-88ba-33d0a461c5d3.png)

- [x] develop a functionality capable of fitting crystal within user's viewport changing zoom / pan
- [x] identify potential opportunities to integrate this functionality
      - [x] after adding an atom to the motif 
      - [x] when displaying an unit cell viewport
      - [x] when generating a png with the "framed" flag

**Comment by ThanosSar** [comment]
Done
