### ISSUE TITLE
WebGL incompatible browsers breaking-up application

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#177]
browsers and systems that are not webgl compatible are displaying a broken-up application without  the webgl canvas. We need to check user's webgl compatibility and display the following warning screen (below) in the case user's computer is not compatible:

“Oops, seems your browser does not support WebGL. Check out Get WebGL, or try installing the latest version of Chrome, or Firefox.”
Get WebGL link - http://get.webgl.org/
Chrome link – https://www.google.com/chrome/ 
Firefox link - https://www.mozilla.org/en-US/firefox/ 

![image](https://cloud.githubusercontent.com/assets/4349542/12816008/09b37ea4-cb31-11e5-96d4-5c55d336449a.png)

**Comment by ThanosSar** [comment]
Done. Alex also has to do some improvments to the warning message and the menu in this case.

**Comment by bardella** [comment]
we need Alex's touch on this one here :)

**Comment by ekaratzaferis** [comment]
Formatting Done.
