### ISSUE TITLE
new about/welcome screen and tutorial mode

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#198]
in short description user access CW and see welcome screen (about). has the option to NEVER see welcome screen again or to enter tutorial mode. 

tutorial mode has 5 steps and will use a custom alert window design: it has a dark gray header (same from footer) with a foot icon (attached). it should not steal focus (windows UAC effect) as other alert boxes we have implemented.

texts and descriptions for the updated welcome / about and 5 steps are below:

# WELCOME SCREEN: First alert that is shown once user access CW – same as the about button (that now needs to be updated)
**Title: Welcome to CrystalWalk**
CrystalWalk is a crystal editor and visualizer software designed for teaching materials science and engineering. Based in WebGL/HTML5, it provides an accessible and interactive platform to students, professors and researchers.

CrystalWalk is an open-source project developed by Fernando Bardella’s Nuclear Technology PhD research at the Nuclear Energy Research Institute (IPEN) / Brazilian National Nuclear Commission (CNEN) at University of São Paulo (USP).

A series of tutorials on how to create and explore crystal structures is accessible at CrystalWalk’s Instructable Channel at http://www.instructables.com/id/CrystalWalk-Collection/ If this is your first time using CrystalWalk, you can access its Interactive Step-By-Step Tutorial by clicking on the button below.
You can also find more information at CrystalWalk project’s page at crystalwalk.org, or reach the author at bardella@ipen.br for any questions, comments or concerns.

###Button 1, left – saves a cookie and prevents user for seen this again: Do not show me this again
###Button 2, right – takes user to tutorial: Take me to the Step-By-Step Tutorial

# Tutorial: design a custom alert with a foot icon (alex)
## Title: Step 1: Choosing a Bravais Lattice
Following the approach of combining Bravais Lattice with a Motif to create a Crystal Structure [ref], CrystalWalk’s first step to take you to the Lattice Tab to create a Crystal Structure is to interactively guide you into choosing a Lattice.
Click at the highlighted menu button at your right and choose between the 14 Bravais + Hexagonal Lattices. And don’t worry if you don’t know what Lattice you should be using in your Crystal Structure, you can return to this tab and change its parameters at any time. Also just keep in mind that your lattice parameters will always be available to you on the Navigation Compass, in highlighted.
Additionally to the main menu, toggle bar will always be available so that you can switch on or off scene elements as abc / xyz axes, lattice points, edges and faces as well planes, directions, atoms and much more.  
###highlights in sequence: 1 choose lattice button 2 Navigation Compass 3 toggle bar, waits user to choose a lattice before proceeding to next step

## Title: Step 2: Composing your Motif
Having chosen your Lattice and its parameters, next step to create a Crystal Structure is to use the Motif Editor tab to interactively guide you into composing your Motif.
Click at the highlighted menu button at your right and add an atom by interactively choosing an ion from the periodic table. CrystalWalk uses the AUTO mode as per default, which assumes prototype structures and the rigid sphere’s model to guess and automatically position your atoms and adjust your lattice parameters. If you are a student its likely all you need to know are the lattice and atoms that compose your motif, although a set of additional parameters is also available if you want to manually position motif atoms at a particular ABSOLUT (in Å) or VECOTORIAL coordinates relative to the crystallographic axys.
Repeat this process as many times as you want, you can always return to this tab.

###(highlights add atom in ME, waits user to add an atom before proceeding to next step)

## Title: Step 3: Visualizing and Interacting 
Congratulations, you have just created your Crystal Structure! 
A few options highlighted at both your left and right sides are now available to help you better visualize it. In Blue at your left you can see both Atom View which can position you in first person at a selected atom location, as well GearBox which can help you transition scales from Lattice points, Motif, different representations of unit cell and Crystal Structure.
In the menu, at your left, a whole lot of visualization tools and options are given. You can explore different types of model representations, rendering parameters and effects as well interacting with your Crystal Structure in 3D using experimental human interaction devices (HID) if your system supports it. 
Just give it a try, you can always do/undo any of the options you choose.
###Button 1: Next Step
###(highlights in sequence Visualization Tab, Atom View and Gear Box; waits user to click on next step button to proceed)

## Title: Step 4: Additional Visualization Resources
At this point a whole set of extra features and resources are available, you can create a diverse planes and directions representation at this tab, as well a didactic narrative with texts, links and animations to illustrate classes and examples. 
Just give it a try, you can always do/undo any of the options you choose.
###Button 1: Next Step
###(highlights in sequence Planes & Directions Tab, Notes Tab; waits for user to click on next step button)

## Title: Step 5: Save Your Project
Going through all of these steps, it’s now time to save your project for later use so that you share them with students and other colleagues. 
After providing some basic information about your project highlighted in the Import / Export tab at your right, several options will become available. You can save your project online at our servers, using our cool cw.gl url shortner and QR code generator services, create bitmap images and even export geometry in the STL format for 3D printing your model.  
Finally you can have access to our online library, search for specific terms / description and open your model at the options menu below. 

Thank you for making to this far! A series of community supported tutorials on how to create and explore crystal structures is accessible at CrystalWalk’s Instructable Channel at http://www.instructables.com/id/CrystalWalk-Collection/ 
You can also find more information at CrystalWalk project’s page at crystalwalk.org, or reach the author at bardella@ipen.br for any questions, comments or concerns.

###Button 1: Close
###(highlights Import / Export Tab)

![footsteps_icon svg](https://cloud.githubusercontent.com/assets/4349542/14222929/b577dcf0-f84d-11e5-8b2d-a79b95a44873.png)

**Comment by bardella** [comment]
will redesign this functionality.

**Comment by ekaratzaferis** [comment]
The starting screen and the tutorial have been implemented, so I'm closing this issue. 

It'll be easier to track any possible bugs in a new issue thread.
