### ISSUE TITLE
url loading in white background

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#199]
after saving a project online, when loading it will insert a white background in the model. apparently previously saved projects are not impacted so I'm not sure the problem in on the saving or in the loading

example here https://crystalwalk.herokuapp.com/#h9

**Comment by ekaratzaferis** [comment]
I've looked into it, values seem to be stored correctly. Maybe this particular example was stored when in fact there was an issue with the background.

I've just created a new project, http://crystalwalk.herokuapp.com/#i8, which does not have this problem.
