### ISSUE TITLE
icons redesign

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#201]
certain icons were used/reused and are not properly representing its correct functions so they need to be redesigned:

- [x] 1. unit cell / crystal model representations
- [x] 2. rendering custom modes, shaders and effects
- some of the existing icons can be re-utilized, but please test their functionality to have its correct representation

- [x] 3. notes icon
- notes are now called comments and narrative, I believe a "movie" icon best represent this functionality
images are below

- [x] 4. motif switcher icon
- we are using the same "camera" icon but I think we could just use the main motif one

![image](https://cloud.githubusercontent.com/assets/4349542/14212512/a3a22dd0-f809-11e5-81d8-6779c48ebac1.png)

![image](https://cloud.githubusercontent.com/assets/4349542/14212541/cfa71f30-f809-11e5-82b2-c55903a46571.png)

![image](https://cloud.githubusercontent.com/assets/4349542/14212877/590ad7a2-f80b-11e5-8b6b-2909603674ae.png)

**Comment by ekaratzaferis** [comment]
1) Redesigned the icons
2) Restored the old lamp icons
3) Designed new comments and narrative icon
4) Replaced the camera icon with the motif icon from the menu ribbon
