### ISSUE TITLE
comments and narrative (former notes) functionalities

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#202]
- [x]  In (1): Allow user to reorganize the items on the list, similar to the atom list behaviour. 
- [x] Within the notes functionality, add the option to save saved camera position at the moment note was saved. 
- [x] Allow user to use the left / right arrows (2) and transition from one note/camera entry to the next in the note list. 

![image](https://cloud.githubusercontent.com/assets/4349542/14212665/566ad124-f80a-11e5-9996-4ec87bffa278.png)
![image](https://cloud.githubusercontent.com/assets/4349542/14212681/66ac0cb0-f80a-11e5-900c-0d7ce309329b.png)

**Comment by bardella** [comment]
so, a few extra changes / comments here related to the behavior of this function:

- [ ] once user clicks on new, he should be able to see the note he has just added. ideally all parameters should be simultaneously reflected on canvas (title / color / field) 
- [ ] on the item list, user should be able to see the color parameter (as in planes/directions)
- the option to save camera position should be a camera icon (button as in visualization) with the following tooltip: CLICK TO ENABLE / DISABLE SAVING CAMERA POSITION

ADD the following interface elements / functionalities:

- at the left of the saving camera position button, add a new button using the MotiffEditor icon with the following tooltip: CLICK TO ENABLE / DISABLE SAVING CRYSTAL SCENE PARAMETERS

we also want to include an automatic transition to take place:
 - [ ] include play / pause /rewind / forward  buttons to do exactly these functions (play/pause/previous slide / next slide) image attached
- [ ] include repeat to have automatic transition as a loop
- [ ] include a slider with the title "Autoplay transition time" which sets the time between transitions (use the one we've used in the sound, parameters are from 5 seconds to 300) 
- [ ] highlight current played slide
- [ ] include in the list box the color of the comment. 

![image](https://cloud.githubusercontent.com/assets/4349542/14615003/06bb6b2a-057a-11e6-82e1-a445690949f7.png)

**Comment by ekaratzaferis** [comment]
List is now reorganizable.
Left / Right arrows loop through the list of notes.

Canvas note is shown as soon as the add button is clicked.
Any change is made on note panel (title,color,body) is reflected to the canvas note.
Added color indicator on the note list.

Added placeholders for save camera icon and enable motif parameters to the note panel.
