### ISSUE TITLE
cw experimental features highlight

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#204]
either add a line/outline or change the background of the following buttons:
- [x] LIGHT ICONS: SSAO and AMBIENT
- [x] ALL UNIT CELL AND CRYSTAL STEREOSCOPIC ICONS
- [x] ALL HUMAN INTERACTION INTERFACE ICONS
- [x] ALL SOUND ICONS
- [x] DOWNLOAD TO YOUR PC ICON

yellow seems more "experimental" but please use the colors and options that you find best

![image](https://cloud.githubusercontent.com/assets/4349542/14214787/4ebde910-f815-11e5-947e-6d6d29b00792.png)

![image](https://cloud.githubusercontent.com/assets/4349542/14214794/58e50112-f815-11e5-9066-3aa7a97fa691.png)

**Comment by bardella** [comment]
Alex, let's go with the background highlight option. (second screenshot option)

**Comment by ekaratzaferis** [comment]
All experimental elements have a highlighted background at the moment.
