### ISSUE TITLE
screenshot functionality stability issues

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#208]
under certain conditions screenshot functionality is not working properly.
here are a few situations I've experienced that need to be further investigated:

- [x] under most window sizes, generating large images with " crystal center"  option enabled is producing some very weird results... particularly on the high resolution images
- [x] different crystal representation modes are discarded when generating the screenshot
- [x] please have the background mode /  qr code / center options disabled as per default

**Comment by ThanosSar** [comment]
under most window sizes, generating large images with " crystal center" option enabled is producing some very weird results... particularly on the high resolution images
- READY

different crystal representation modes are discarded when generating the screenshot
- READY

**Comment by ThanosSar** [comment]
assigned "please have the background mode / qr code / center options disabled as per default" to alex

**Comment by ekaratzaferis** [comment]
Snapshot Options disabled by default.
