### ISSUE TITLE
vectorial mode issues / adjustments

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#217]
- [x] VECTORIAL and ABSOLUT indexes (abc/ xyz) are switched. (please see images below). please have VECTORIAL with abc and ABSOLUT with xyz and also check for any additional inconsistencies.

- [x] tooltips for abc/xyz are different for VECTORIAL and ABSOLUT. please read the tooltip to see the **** on where it has to be changed

- [x] when in VECTORIAL, HEXAGONAL atoms positions are acting as absolute. if you add MG 2 atoms in a cubic lattice, one in position 000 and the other in position 111, you will see that changing lattice parameters will no change atoms proportionally (they will act as ABSOLUT). seems this issue is intermittent (not sure was fixed this morning as well)

![image](https://cloud.githubusercontent.com/assets/4349542/14649275/a652294a-063c-11e6-9dda-878a5bc4aede.png)

![image](https://cloud.githubusercontent.com/assets/4349542/14649288/ad656616-063c-11e6-9246-853fbd64d844.png)

**Comment by ThanosSar** [comment]
fixed
