### ISSUE TITLE
planes and directios indexes in hexagonal

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#218]
- [ ] add a forth index ( i ) in hkil mille-bravais indexes for planes. forth index needs to be calculated automatically, so that user enters only 3 coordinates.  ( i = - ( h + k) ), l is always l

- [ ] add a forth index ( i ) in uvtw mille-bravais indexes for planes. forth index needs to be calculated automatically, so that user enters only 3 coordinates.  ( t = - ( u + v) ), w is always w

![image](https://cloud.githubusercontent.com/assets/4349542/14651898/4246db60-0648-11e6-816c-5d83b42c3e38.png)

**Comment by ThanosSar** [comment]
DONE

**Comment by ekaratzaferis** [comment]
Added the auto-calculation of Miller I and Miller T parameters, every time the user types a value on the Miller H,K,U,V inputs.

Thanos has already enabled the appearance of the Miller I,T inputs underneath the HKL or UVW.
