### ISSUE TITLE
narratives slide switching issue

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#226]
for now, clicking on the item list should show only the not selected. for some reason it's showing all the created notes at the same time (see image)

![image](https://cloud.githubusercontent.com/assets/4349542/14931272/734553ea-0e40-11e6-80b5-beb717552e35.png)

**Comment by ekaratzaferis** [comment]
Do you mean that the maximum number of visible notes in canvas should be 1?

Could you please write down the steps that produce this bug?

Maybe Thanos has already fixed it, but I can't reproduce it.

**Comment by bardella** [comment]
its actually a simpler issue here... basically once user clicks on a particular item on the narrative list it should display ONLY its comment and hide the other comments  (just like when clicking on the next button). 

Right now once users click on the item list, it shows all of them at the same time (see pic)


![image](https://cloud.githubusercontent.com/assets/4349542/22848438/8787e944-efdb-11e6-9ce4-8b00677a2697.png)

**Comment by ekaratzaferis** [comment]
Fixed.

When user selects a note, it becomes visible and all the others are hidden.

User can still view multiple notes at once, by clicking on the visibility (eye) button, which still shows/hides a single note.
