### ISSUE TITLE
lattice button image adjustments

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#228]
we need to make a couple lattice button image adjustments

a. remove simple from hexagonal
b. edit the primitive lattice to make the primitive cell more evident (see image below). you can gray out / dotline the non main parts as highlited on the picture below
![image](https://cloud.githubusercontent.com/assets/4349542/14932204/4ab47722-0e49-11e6-94c1-14a572a1636b.png)

**Comment by AndScientist** [comment]
Strange was better
Em 29/04/2016 20:31, "Fernando Bardella" <notifications@github.com>
escreveu:

**Comment by ekaratzaferis** [comment]
I edited the Hexagonal Primitive icon just as you suggested.

I also removed the Simple label from the Hexagonal Simple item.
