### ISSUE TITLE
colapsing menu behaviour

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#231]
clicking on a menu bar button (2) -> menu expands (3)
clicking on hide/unhide button (1) -> menu closes
clicking on hide/unhide button (1) when menu is closed -> menu colapses
clicking on on hide/unhide button (1) when menu is collapsed -> menu expands back

![image](https://cloud.githubusercontent.com/assets/4349542/15134626/3c0af5d6-1644-11e6-8bd9-0ac2009b2042.png)

desktop default behavior: user starts application with menu hiden. 
mobile phone default behavior: user starts application with menu collapsed. 

note: clicking outside the menu (4) should no longer hide the menu as today. user has to explicitly click on hide for this action.  

(1) icons should be:
hide/unhide - as per today's 
colapse / expand - 3 arrows up / down (example below, using the same style as we are using)
![image](https://cloud.githubusercontent.com/assets/4349542/15134730/4bf30ff0-1645-11e6-9070-8a23c847fdae.png)

**Comment by ekaratzaferis** [comment]
(4) Do you mean clicking on the canvas? I'm clicking and dragging the canvas at the moment and the menu does not hide.

**Comment by fernandobardella** [comment]
You got it

On Tuesday, May 17, 2016, Alexandros <notifications@github.com> wrote:

> (4) Do you mean clicking on the canvas? I'm clicking and dragging the
> canvas at the moment and the menu does not hide.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gvcm/CWAPP/issues/231#issuecomment-219769743>
>


-- 
Sent from Gmail Mobile

**Comment by ekaratzaferis** [comment]
Now, the old open/close button:
  - Closes the menu when it's open.
  - Hides it when the menu is closed. It also shows a new button, that unhides the menu when it's clicked.

By default, when the application is loaded on a mobile device, the menu is hidden.
