### ISSUE TITLE
issues with unhiding menu on phone

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#233]
clicking on unhiding menu button (1) on phones is very difficult because user actually needs to click at the image we are using, which is small on the phone screen
![image](https://cloud.githubusercontent.com/assets/4349542/15518587/a6d47c6a-21cb-11e6-88cc-869547261d7a.png)

My recommendation is that we keep a grey button boundary clickable area, as we are doing with the hiding button (2). 
![image](https://cloud.githubusercontent.com/assets/4349542/15518572/91290eda-21cb-11e6-8586-39e5fe4f4946.png)

**Comment by ekaratzaferis** [comment]
Done
