### ISSUE TITLE
lattice edges and faces instabilities in ME

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#238]
Lattice edges and faces in ME
 are acting weirdly, please look at the picture
1: lattice edges and faces are perfect (1)
2: is not showing lattice points not faces
3: is not showing anything... is all black

![i2 cimgpsh_orig](https://cloud.githubusercontent.com/assets/4349542/16847530/e2bc4b94-49c7-11e6-8501-5c6a820898d3.png)

they should all be controlled by toggle

**Comment by ThanosSar** [comment]
solved

**Comment by bardella** [comment]
solved
