### ISSUE TITLE
Atom positioning precision issue

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#239]
We are experiencing again imprecision issues when placing atoms in the vectorial position:

1: I've added an atom on the position 3/4 3/4 3/4   : 0.75 0.75 0.75
2: after saving it it becomes 0.74 0.74 0.74 

Is this related to the positioning of the atom or is this related to how we calculate and display precision of the parameter?  Can you ensure we fix this? 

I also wanted to ensure we use a 4 precision number across all interfaces (as we do in lattice)

![image](https://cloud.githubusercontent.com/assets/4349542/16849053/1214a39e-49cf-11e6-9520-25f473eb9725.png)

![image](https://cloud.githubusercontent.com/assets/4349542/16849055/15e5e0a0-49cf-11e6-96df-4ffc7ea758dc.png)

**Comment by ThanosSar** [comment]
I think I have solved it.

**Comment by bardella** [comment]
... it has improved... but not quite; look at the same example of the 3/4 and saving
![image](https://cloud.githubusercontent.com/assets/4349542/17879297/46119c30-68c7-11e6-8df1-8fec6e0809f9.png)

**Comment by bardella** [comment]
done!
