### ISSUE TITLE
Bravais Lattice selection for Hexagonal

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#241]
We need to implement the following adjustment:

1: hide "hexagonal strange"  icon per default
2.: once user slides over hexagonal primitive, we display "hexagonal strange" a bit grayed out giving user the option to click on it
3: " hexagonal strange"  icon disappears after a few seconds user removes mouse from  
Lastly, can we ensure all rows here have the same width? 

![image](https://cloud.githubusercontent.com/assets/4349542/16849658/dff1e3ec-49d1-11e6-9ed3-d0da68d3bbfc.png)

![image](https://cloud.githubusercontent.com/assets/4349542/16849722/2b27320e-49d2-11e6-9c35-70d77715452b.png)

**Comment by ekaratzaferis** [comment]
Hexagonal Strange tile has now a low opacity value, 0.2.

While user hovers on top of it, it goes up on 1.0 again.

Changed the tooltip and added the warning that it's not a bravais lattice.

Lastly, I fixed the column with in the table to be the same in every tile.
