### ISSUE TITLE
Hexagonal axis issue

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#243]
seems to me that hexagonal unit cell / crystal structure lattices'  axis are not the same (please take a look on the image)

![image](https://cloud.githubusercontent.com/assets/4349542/16850010/7ddfc0c8-49d3-11e6-8519-916733626251.png)

**Comment by bardella** [comment]
seems this is the same on Motif X , Y  and Z axis... they all need to follow the toggle selection

**Comment by ThanosSar** [comment]
solved

**Comment by bardella** [comment]
solved
