### ISSUE TITLE
custom element radii option

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#253]
add the option for user to add custom radius on the atom element. make it savable / restorable 
![image](https://cloud.githubusercontent.com/assets/4349542/18417950/99508cc0-7813-11e6-9c2d-370613340668.png)

**Comment by ekaratzaferis** [comment]
Done.

Whenever the user select an atom from the periodic table, focus goes on the Custom field next to the fixed ionic index values.

User HAS to type a number and press Enter, otherwise no custom value can be added. 

User can click and select the standard values as usual.
