### ISSUE TITLE
hex strange atom vect positioning

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#254]
vect coordinates in hex strange is broken (see pic). 

- [x] fix hex vect coordinates
- [x] add forth index and display atom's coordinates in hkil and uvtw format @atomlist

 ![image](https://cloud.githubusercontent.com/assets/4349542/18552915/eda7e3b2-7b34-11e6-85a5-c7c872a5ace2.png)

**Comment by ThanosSar** [comment]
i think's done. I haven't tested it thoroughly though.
