### ISSUE TITLE
database error

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#270]
saving json data is not working

**Comment by bardella** [comment]
so, I just found out that issue presents itself once user adds an atom to the scene... if no atoms are added, you can save / restore it without any problems... I believe this may be related to our last update to it. please find a screenshot below

![image](https://cloud.githubusercontent.com/assets/4349542/20833397/a6c51cec-b876-11e6-9e30-e0429e546c00.png)

**Comment by ekaratzaferis** [comment]
JSON is now created correctly, so the Save Online feature works once again properly.
