### ISSUE TITLE
QR code behaviour issue

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#279]
User is unable to see QR code if he actually opens a saved project. Example, if user follows cw.gl/kj this is what he gets: 
![image](https://cloud.githubusercontent.com/assets/4349542/22848580/bc74bc1c-efdc-11e6-9dc1-d330b80eaf3c.png)

Correct behaviour for opened projects should be user ALWAYS gets the QR code / URL, then it gets updated in the case user saves / resaves

![image](https://cloud.githubusercontent.com/assets/4349542/22848668/2d2676b2-efdd-11e6-8266-d519c0448bb7.png)

**Comment by ekaratzaferis** [comment]
This was on the UI, so I took care of it.

When a project is loaded from our database using the url+slug (cw.gl/kh for example), the link under the Save Online button is already visible, and the QR image is generated.
